export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';




export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const  PRODUCTS_NOT_FOUND = 'PRODUCTS_NOT_FOUND'

export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';
export const GET_PRODUCTS_SUCCESS_BY_ID = 'GET_PRODUCTS_SUCCESS_BY_ID';
export const GET_PRODUCTS_FAIL_BY_ID = 'GET_PRODUCTS_FAIL_BY_ID';


export const ADMIN_LOADED ='ADMIN_LOADED'
export const AUTH_ERROR_ADMIN = 'AUTH_ERROR';
export const LOGIN_SUCCESS_ADMIN = 'LOGIN_SUCCESS';

export const LOGIN_FAIL_ADMIN = 'LOGIN_FAIL';
export const AUTH_ADMIN_ERROR = 'AUTH_ADMIN_ERROR';

export const GET_USERS = 'GET_USERS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const  USERS_NOT_FOUND = 'USERS_NOT_FOUND'




export const DELETE_USER = 'DELETE_USER'
export const DELETE_ERROR = 'DELETE_ERROR'
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'



export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_ERROR = 'ADD_ERROR'
export const ADD_REQUEST = 'ADD_REQUEST'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_ERROR = 'DELETE_ERROR'
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'